dist: bionic
language: node_js
node_js:
  - '10'
  - '12'
  - node

cache: yarn

install:
  - yarn install

script:
  - yarn run build
  - yarn run test
  - yarn run lint

deploy:
  provider: npm
  email: jakub@jirutka.cz
  api_key:
    secure: TODO
  skip_cleanup: true
  on:
    tags: true
    node_js: '10'
